# Watchtower (Automated Docker Updates)
version: "3.8"
services:
  watchtower:
    image: ${WATCHTOWER_IMAGE:-containrrr/watchtower:latest}
    container_name: watchtower
    hostname: watchtower
    environment:
      - TZ=${TZ:-Africa/Johannesburg}
      - WATCHTOWER_ROLLING_RESTART=true
      - WATCHTOWER_MONITOR_ONLY=false
      - WATCHTOWER_SCHEDULE=0 0 6 * * ?
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_NOTIFICATIONS=slack
      - WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL=${WATCHTOWER_NOTIFICATION_DISCORD_HOOK_URL}
      - WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER=${WATCHTOWER_MSG_NAME}
      - DOCKER_HOST=tcp://socket-proxy:2375
      - DOCKER_API_VERSION=1.48
      # - WATCHTOWER_HTTP_API_TOKEN=xxx
      # - DOCKER_CONFIG=/config
      # - REPO_USER=youruser
      # - REPO_PASS=yourpass
      # - WATCHTOWER_NO_RESTART=true
      # - WATCHTOWER_SCOPE=myscope
    networks:
      - internal
    restart: unless-stopped
    stop_grace_period: 30s
    security_opt:
      - no-new-privileges:true
    labels:
      log_name: "watchtower"
      prometheus.scrape: "true"
      prometheus.port: "8080"
      prometheus.path: "/metrics"
networks:
  internal:
    external: true
    name: ${INTERNAL_NETWORK:-internal}
