# Duplicati (Backup Service)
version: "3.8"
services:
  duplicati:
    image: ${DUPLICATI_IMAGE:-linuxserver/duplicati:latest}
    container_name: duplicati
    hostname: duplicati
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Africa/Johannesburg}
    volumes:
      - ${DOCKERDIR:-/home/homelab/conf}/duplicati/config:/config
      - ${DOCKERDIR:-/home/homelab/conf}/duplicati/backups:/backups
      - ${DOCKERDIR:-/home/homelab/conf}/duplicati/source:/source
    restart: unless-stopped
    stop_grace_period: 30s
    security_opt:
      - no-new-privileges:true
    networks:
      - internal
      - external
    labels:
      log_name: "duplicati"
      prometheus.scrape: "true"
      prometheus.port: "8200"
      prometheus.path: "/metrics"
      traefik.enable: "true"
      traefik.docker.network: "external"
      traefik.http.routers.duplicati.tls: "true"
      traefik.http.routers.duplicati.entrypoints: "https"
      traefik.http.routers.duplicati.rule: "Host(`duplicati.cityzen.co.za`)"
      traefik.http.routers.duplicati.middlewares: "authelia@docker,no-poweredby@docker,even-less-secure-headers@docker"
networks:
  internal:
    external: true
    name: ${INTERNAL_NETWORK:-internal}
  external:
    external: true
    name: ${EXTERNAL_NETWORK:-external}
