# docker-compose.yml for Tautulli (from holo-deck stack)
# Strictly follows FORMATTING.md and user rules.
version: '3.8'
services:
  tautulli:
    image: ${TAUTULLI_IMAGE:-lscr.io/linuxserver/tautulli:latest}
    container_name: tautulli
    hostname: tautulli
    environment:
      - PUID=${PUID:-1000}                   # User ID for file permissions
      - PGID=${PGID:-1000}                   # Group ID for file permissions
      - TZ=${TZ:-Africa/Johannesburg}        # Timezone
      - DOCKER_MODS=ghcr.io/themepark-dev/theme.park:tautulli # ThemePark mod
      - TP_THEME=plex                        # ThemePark theme
    volumes:
      - ${DOCKERDIR:-home/homelab/conf}/tautulli:/config  # Persistent Tautulli config
    networks:
      - internal
      - external
    restart: unless-stopped
    stop_grace_period: 30s
    security_opt:
      - no-new-privileges:true
    ports:
      - "8181:8181" # Tautulli UI
    # labels:
      # 📹 Logging/Monitoring
      # log_name: "tautulli"                                         # Logging tag
      # 🚀 Traefik Enablement
      # traefik.enable: "true"                                       # Enable Traefik reverse proxy
      # traefik.docker.network: "external"                           # Traefik network
      # 🎯 Traefik Routing/Rules
      # traefik.http.routers.tautulli.tls: "true"                    # Enable TLS
      # traefik.http.routers.tautulli.entrypoints: "https"           # HTTPS entrypoint
      # traefik.http.routers.tautulli.rule: "Host(`plexstats.cityzen.co.za`)" # Domain routing rule
      # traefik.http.routers.tautulli.middlewares: "authelia@docker,less-secure-headers@docker,no-poweredby@docker" # Security middleware
networks:
  internal:
    external: true
    name: ${INTERNAL_NETWORK:-internal}
  external:
    external: true
    name: ${EXTERNAL_NETWORK:-external}