version: '3.8'

services:
  chatwoot:
    image: chatwoot/chatwoot:latest
    container_name: chatwoot
    env_file:
      - stack.env     
    depends_on:
      - chatwoot-db
      - chatwoot-redis
    command: ["bundle", "exec", "rails", "s", "-b", "0.0.0.0", "-p", "3000"]     
    networks:
      - external
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=homelab"
      - "traefik.http.routers.chatwoot.rule=Host(`chat.cityzen.co.za`)"
      - "traefik.http.routers.chatwoot.entrypoints=https"
      - "traefik.http.routers.chatwoot.tls=true"
      - "traefik.http.routers.chatwoot.middlewares=authelia@docker,chatwoot-large-headers@docker"
      - "traefik.http.services.chatwoot.loadbalancer.server.port=3000"

      # Custom headers middleware
      - "traefik.http.middlewares.chatwoot-large-headers.headers.customrequestheaders.X-Forwarded-Host=chat.cityzen.co.za"
      - "traefik.http.middlewares.chatwoot-large-headers.headers.customresponseheaders.X-Frame-Options=SAMEORIGIN"
      - "traefik.http.middlewares.chatwoot-large-headers.headers.customresponseheaders.X-Fix=Enabled"
      - "traefik.http.middlewares.chatwoot-large-headers.headers.contentTypeNosniff=true"

      
  chatwoot-worker:
    image: chatwoot/chatwoot:latest
    container_name: chatwoot-worker
    env_file:
      - stack.env    
    depends_on:
      - chatwoot-db
      - chatwoot-redis
    command: ["bundle", "exec", "sidekiq"]     
    networks:
      - external

  chatwoot-db:
    env_file:
      - stack.env     
    image: pgvector/pgvector:pg16
    container_name: chatwoot-db
  
    volumes:
      - /home/homelab/conf/chatwoot/postgres-data:/var/lib/postgresql/data
    networks:
      - external

  chatwoot-redis:
    image: redis:6-alpine

    container_name: chatwoot-redis
    command: redis-server --save 1 900 --save 5 300
    volumes:
      - /home/homelab/conf/chatwoot/redis-data:/data
    networks:
      - external



networks:
  external:
    external: true
