version: "3.8"
services:
  traefik:
    image: traefik:${TRAEFIK_VERSION:-latest}
    container_name: traefik
    restart: always
    networks:
      - internal
      - external
    security_opt:
      - no-new-privileges:true
      - seccomp=conf/seccomp/traefik-seccomp.json
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - ${DOCKERDIR:-/home/homelab/conf/traefik}/traefik/rules:/rules
      - ${DOCKERDIR:-/home/homelab/conf/traefik}/traefik/acme.json:/acme.json
      - /var/log/traefik:/logs
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - CLOUDFLARE_DNS_API_TOKEN=${CLOUDFLARE_DNS_API_TOKEN}
      - DOCKER_API_VERSION=1.48
    command:
      - --global.checkNewVersion=true
      - --log.level=DEBUG
      - --log.filePath=/logs/traefik.log
      - --accessLog=true
      - --accessLog.filePath=/logs/access.log
      - --accessLog.bufferingSize=100
      - --serversTransport.insecureSkipVerify=true
      - --entryPoints.http.address=:80
      - --entryPoints.https.address=:443
      - --entrypoints.http.http.redirections.entryPoint.to=https
      - --entrypoints.http.http.redirections.entryPoint.scheme=https
      - --entrypoints.https.http.tls.options=default
networks:
  internal:
    driver: bridge
    name: internal
  external:
    external: true
    name: external
